### ISSUE TITLE
トップページ（ログインしていない状態でアクセスがきたら）デザイン

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#10]
## WHY
コーディングに入るため

**Comment by kota226** [comment]
![png](https://cloud.githubusercontent.com/assets/19641578/17427874/06a90160-5b1f-11e6-9b2e-e2f984956ab8.png)

**Comment by kota226** [comment]
![default](https://cloud.githubusercontent.com/assets/19641578/18031454/785b2c20-6d1c-11e6-8196-f2910bd47ea4.png)

**Comment by kota226** [comment]
一応ログイン済みの場合のトップもUPしときます
未ログインのページと若干デザインの異なる部分があるため別途議論する必要がありそうです
![-1](https://cloud.githubusercontent.com/assets/19641578/18031564/cf73d616-6d20-11e6-8494-bf16f1c1e151.png)
