### ISSUE TITLE
仮リリースに向けてのToDo確認&実行

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#105]
## WHY

明日の仮リリースに向けて何をしているのか、何をすべきかを各々把握できていない。

## WHAT

各々ToDoを書いていき、その下に問題(困っていることや相談したいこと)を書いていってください。

書いたToDoは明日18時のリリースまでに実行してもらいます。

**Comment by SoyaTakahashi** [comment]
## ToDo

- [ ] マイページのコーディング
- [ ] プロフィール更新ページのコーディング
- [ ] 各ページにデータを紐づける


## 困っていること

いろいろありすぎてもはや分からないw

**Comment by kota226** [comment]
## ToDo
担当ページのデザインの再確認
- リリース準備までに取り除ける不具合は無いか
- 現行のデザインで高齢者に見やすく操作しやすいか、ユーザ目線になって見直す

新規ページ追加の検討
- つぶやきのみ、ブログのみの一覧を表示するページなど

仮リリースに必要な知識、情報等の収集
- おもにAWSのセキュリティ関連

**Comment by KarenNakayama** [comment]
## TODO

にぎわいサロンページ

- [ ] 「にぎわいサロンとは？」の箇所のデザインを申し工夫
- [ ] 成り立ち、講座内容一覧、開催場所のモーダル


つぶやきページ

- [ ] 中央寄せにした、container を使ったものにする

**Comment by kaorioyama** [comment]
##ToDo

ブログ投稿ページ

- [ ] 送信ボタンが中央に行かない
- [ ] 中寄せができていない

**Comment by MaiKambe** [comment]
## ToDo

- [ ] Ruby開発環境を再インストール

地域情報ページ

- [ ] タイトル上に余白

- [ ] 画像位置及び文字位置の調整


通知ページ

- [ ] タイトル上に余白

- [ ] 背景を白色に

## 困ったこと
rails 実行できない

**Comment by KarenNakayama** [comment]
## 困ったこと

- [ ] つぶやきページの中央寄せができないこと

**Comment by SoyaTakahashi** [comment]
@KarenNakayama 

自分のコメントを編集してそこに記載ください。
