### ISSUE TITLE
各ページのデザイン見直し

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#106]
## WHAT

各ページのデザインを見直す。
- デザインはおかしくないか
- データを紐づけれるUIになっているのか

各ページ

髙橋
- [x] ヘッダー

矢倉先輩
- [x] トップページ
- [x] 投稿一覧
- [x] ブログ一覧
- [x] つぶやき一覧

かれんさん
- [x] お問い合わせページ
- [x] にぎわいサロン予約ページ
- [x] つぶやき投稿ページ

大山さん
- [x] 新規登録ページ
- [x] ログインページ
- [x] ブログ投稿ページ

神戸さん
- [x] 地域情報ページ
- [x] 通知ページ

## WHY

仮リリースに向けておかしなデザインがあったらリリースできない。
データを紐づけるにあたって、おかしなUIがあったらデータを紐付けできない。

**Comment by SoyaTakahashi** [comment]
## トップページ

**Comment by SoyaTakahashi** [comment]
## 投稿一覧

- 中央揃えになっていない。`container` を当ててあげる必要がある。
- 「つぶやきを投稿する」と「ブログを投稿する」ボタンの間のスペースが空きすぎです。
<img width="1152" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20472088/366b248e-affa-11e6-9211-b05abeb19a7b.png">
-

**Comment by SoyaTakahashi** [comment]
## お問い合わせページ

- リンク先が全てユーザのマイページになっているので、正しいリンクになおしてほしい。

**Comment by SoyaTakahashi** [comment]
## にぎわいサロン予約ページ

- 「にぎわいサロンとは？」の箇所のデザインを申し工夫してほしいです。

**Comment by SoyaTakahashi** [comment]
## つぶやき投稿ページ

- 中央寄せにしたい。そもそも `container` を使用してほしい。
- 送信ボタンが小さいw

**Comment by SoyaTakahashi** [comment]
## ブログ投稿ページ

- 中央寄せにしたい。そもそも `container` を使用してほしい。

**Comment by KarenNakayama** [comment]
お問い合わせページの修正完了しました。
PRもつくったので宜しくお願いします。

**Comment by SoyaTakahashi** [comment]
## 地域情報ページ

- タイトルと内容も含めたい。し、デザインも調整したいです。
<img width="1252" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20474751/850b4d1a-b00b-11e6-9fd5-4ab908faf285.png">

**Comment by SoyaTakahashi** [comment]
@KarenNakayama 
> お問い合わせページの修正完了しました。

見ます！

**Comment by SoyaTakahashi** [comment]
## 通知ページ

- 「通知ページ」の上に余白がほしいです！
- boxの背景は白です。

**Comment by SoyaTakahashi** [comment]
# 木曜日まで

**Comment by kota226** [comment]
投稿一覧ページの修正完了しました。また、ブログを投稿するボタンにも鉛筆アイコンを表示させて統一感を出させました。

**Comment by SoyaTakahashi** [comment]
## 新規登録ページ

- 登録ボタンのデザインがやばいことになっています。笑bootstarapのボタンを使うといいかも！
<img width="955" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20663846/4fec9a94-b59c-11e6-9b84-a1d1498c8746.png">

**Comment by SoyaTakahashi** [comment]
## ログインページ

- 全体的にもうちょっとフォームとフォントサイズを小さくしたいです。ちょっとでかすぎるかも。
- ログインボタンのデザイン崩れてます。
<img width="978" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20664050/08c2f4a0-b59d-11e6-925f-52e67523a8e4.png">

**Comment by SoyaTakahashi** [comment]
## つぶやき一覧

- 「ブログを見る」、「つぶやきを投稿する」の色や装飾を工夫してください。
<img width="987" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20664898/9a060986-b5a0-11e6-8158-cb538ee5cb4b.png">

- 「返信する」ボタンのフォーカス時のデザインが古いです。今風なデザインにしましょう！
<img width="964" alt="sns" src="https://cloud.githubusercontent.com/assets/11175160/20664960/ebec530e-b5a0-11e6-99e2-e89f4eac4167.png">
