### ISSUE TITLE
投稿一覧（トップ）デザイン

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#11]
## WHY
コーディングに入るため

**Comment by kota226** [comment]
![default](https://cloud.githubusercontent.com/assets/19641578/18031456/a2f1ff5e-6d1c-11e6-8acf-16862fe12a53.png)

**Comment by kota226** [comment]
以下はメッセージ投稿のページになります
![sns-1](https://cloud.githubusercontent.com/assets/19641578/18031551/36377c1e-6d20-11e6-9b58-30d99996d1a1.png)
