### ISSUE TITLE
各ページのデザイン

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#2]
## WHAT

高齢者向けSNSに必要な各ページのデザイン
## WHY

実際にデザインを見ながらコーディングを開始するため

**Comment by SoyaTakahashi** [comment]
## 必要なページ一覧
- ログイン/サインアップ画面
- トップページ（ログインしていない状態でアクセスがきたら）
- 投稿一覧（トップ）
- 地域情報
- 通知ページ
- にぎわいサロン予約ページ
- マイページ
- お問い合わせページ
- 管理画面

**Comment by SoyaTakahashi** [comment]
3人に担当を振っていると思うけど、担当がふられていないページがある気がする、、

**Comment by SoyaTakahashi** [comment]
# 第一回FB
## 全体
お疲れ様です。
矢倉さんの言う通り、全体としてデザインが統一されていないです。前提として同じサイトなのでデザインが統一されていないのはおかしいですね、、
本来ならば、このようにデザインが統一されなくなってしまうので一つのサイトのデザインは一人が担当した方がいいです。
今回は3人でサイトのデザインをしたいとの意見があったのでそうしましたが、一人がサイトのデザインを担当するべきだったのかもしれません。
## 神戸さん
全体として良いと思います！
高齢者の方を意識して作られているデザインだと思います。
機能面について疑問があります。
- `掲示板`ではなく、`投稿一覧`という形になったはずですが、なんで`掲示板`にしたのですか？
- `トップページ`は、ログインしている画面は投稿一覧のページが、ログインしていなければトップページ（地域情報、にぎわいサロンの紹介）のページが表示されると思うので2つのパターンの画面デザインが必要だと思います。現状だと、投稿一覧がどのようなデザインなのか全くわかりません、、
- あとカレンダーはプラスアルファの機能なので、まだなくて大丈夫です。
最後にフッターが2行になっている理由とかありますか？
1行でよいと思います！
## 大山さん
ヘッダーの色個人的にすごくいいと思います！
ただ掲示板担当ということでしたが、そもそも掲示板の機能はないという認識でした！
投稿一覧のことですか？
## 中山さん
地域情報ページのデザインということでデザインしてもらったと思うんですけど、現状のデザインだと写真がはってあるだけで
どのように情報を伝えたいのか分からないですし、どのようなデザインになるのか分かりません。
それと、矢倉さんもいっていますが前回の話でカレンダー機能はプラスアルファの機能となったので不要となりました。
伝えきれていなくて申しわけないです、、

**Comment by kota226** [comment]
必要な機能
投稿一覧にブログ＆つぶやき両方搭載（スローネット）
写真投稿機能
返信機能（ツイートなどのメッセージに対する）
イベント募集機能
地域情報機能
にぎわいサロン機能
プライベート機能
検索機能
問い合わせ機能

後回しでいい機能
カレンダー

**Comment by kota226** [comment]
以下FB
神戸さんのやつから簡単に感想言っちゃうと
・一般的なWebサイトにあるものを意識して作られている（フッター、お問合せ用のリンクなど）
・テーマカラーと、１つ１つのブロック（機能）が統一されてて見栄えが良い
・「トップページ」～「にぎわいサロン」のトップメニューの配置を他の要素と合わせると洗練された感じになる
・掲示板部分の表示方法が気になる
てところかな

**Comment by kota226** [comment]
大山さんのは
・ボタンやコンテンツの端っこが整理されていて見やすい
・タイトルを独自に考えてくれたので、これを参考に最終的なタイトルを考えるのもあり
・地域情報とカレンダーの縦幅が広いので、ここを小さくして掲示板の縦幅を長くするといい（個人的には地域情報の欄をなくしてトップメニューからフッターまで掲示板スペースとして使うのもありかなと思う）
・トップメニューのボタンの幅を統一するとクリックし易く見た目も良くなる
というところ

**Comment by kota226** [comment]
中山さんのは
・タイトルが大きく、パッと見てどういうページなのかが理解し易い
・１つ１つのエリアも大きめに取られていて、お年寄りにも見えやすい文字で情報を載せ易い
・全体的にカラフルで堅苦しさが無いので、利用者に受け入れやすそうな感じではある？（今後どのような方向性でデザインするのかにもよるが）
・イベント欄の情報の切り替え方を考える必要がある（おそらく全てのイベント情報が画面内に収まるとは限らない）

**Comment by kota226** [comment]
それと、簡単なデザインのコンセプトを決めて、それをもとに作るのが良いと思います。たとえば
　
・地域の特色を生かした独自性の強いもの
・SNSらしさを前面に出して他と簡単につながれると思えるもの
・高齢者層にも優しい色使い、文字の種類や大きさで作りシニア向けSNSであることを意識したもの
・北坂戸SNSという存在（ブランド）を知ってもらうためのもの
・北坂戸団地内の住人だけが使える特別性を売りとするもの
　
この中の全部を採用しなければいけないというわけではありませんが、こういったコンセプトをいくつか書いてみて、その中で良さげなものを１つないし複数選んでデザインの修正に移っていくというのはどうでしょう？

**Comment by kota226** [comment]
webサイトに限らず、スマホアプリや広告など、たいていのデザインには大まかな方針であるコンセプトに沿って作られるので、この機会に決めてしまう方が良いかと

[10:37]  
まぁ、今回のフィードバックを一言でまとめると「皆バラバラのデザインだから大まかな方向性を決めて統一させていった方がいいよね」ということですかね

[10:42]  
まぁ、これはもっとも描く前から決めておくべきことだったので、手順が逆となってしまったのは申し訳ないですが。。

**Comment by SoyaTakahashi** [comment]
## 決定事項
- 7/4（月）にぎわいサロンで、「メインカラーが何色がいいか」「ヘッダー、フッダー」のデザインは3つのデザインでどれがいいか聞いてくる
- ヘッダー、フッダーなどの共通部分は担当をふって作ってもらい、それをみんなで使う

**Comment by SoyaTakahashi** [comment]
- 7/4（月）にぎわいサロンで、「メインカラーが何色がいいか」「ヘッダー、フッダー」のデザインは3つのデザインでどれがいいか聞いてくる

１番いいのに２票、２番めにいいのに１票で６人に聞いた所
まいちゃん、自分と同率でした。
色は、青が多かったです。
ただ薄いのがいいって人が多かったです。
あと四季にあわせた色っていう意見もありました。以上です

**Comment by SoyaTakahashi** [comment]
## 1回目デザイン案

- @MaiKambe 
![sns](https://cloud.githubusercontent.com/assets/11175160/16672582/ff166c6a-44e1-11e6-8af4-c1c00775a8a6.png)

- @kaorioyama 
[SNS.pdf](https://github.com/KanseiLab/sns/files/353216/SNS.pdf)

- @かれんさん
[名称未設定-6.pdf](https://github.com/KanseiLab/sns/files/353217/-6.pdf)

**Comment by SoyaTakahashi** [comment]
![default](https://cloud.githubusercontent.com/assets/19641677/16876268/379680be-4ade-11e6-895c-110616ba8558.png)
![default](https://cloud.githubusercontent.com/assets/19641677/16876266/3775716c-4ade-11e6-9463-0138f1544217.png)

まいさんのデザインで自分配置にさせてもらいました。
掲示板は投稿一覧の間違えです(； ･`д･´)
アイコンは適当なので悪しからず。

**Comment by SoyaTakahashi** [comment]
## かおりさんデザイン

![_____________720](https://cloud.githubusercontent.com/assets/11175160/17088747/553162c8-525a-11e6-9a26-467adeec8dc0.png)

**Comment by SoyaTakahashi** [comment]
## 必要なページ一覧
- ログイン/サインアップ画面
- トップページ（ログインしていない状態でアクセスがきたら）
- 投稿一覧（トップ）
- 地域情報
- 通知ページ
- にぎわいサロン予約ページ
- マイページ
- お問い合わせページ
- 管理画面

**Comment by kaorioyama** [comment]
ログイン/サインアップ画面
トップページ（ログインしていない状態でアクセスがきたら）
投稿一覧（トップ） 大山
地域情報　神戸
通知ページ
にぎわいサロン予約ページ　中山
マイページ
お問い合わせページ
管理画面

**Comment by kota226** [comment]
![sns](https://cloud.githubusercontent.com/assets/19641578/17090188/4b19ccbc-5269-11e6-832d-05589d4e8757.png)
SNS閲覧ページ

**Comment by SoyaTakahashi** [comment]
ログイン/サインアップ画面　大山
トップページ（ログインしていない状態でアクセスがきたら）　矢倉先輩
投稿一覧（トップ） 大山・矢倉先輩
地域情報　神戸
通知ページ　神戸
にぎわいサロン予約ページ　中山
マイページ　大山
お問い合わせページ　中山
管理画面　矢倉先輩
