### ISSUE TITLE
仮リリース(2016/12/06)のToDo

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#202]
## WHY

明日の仮リリースに向けて各々が何をしているか何をすべきかを全員が把握するため。

## WHAT

各々ToDoを書いていき、その下に問題(困っていることや相談したいこと)を書いていってください。

書いたToDoは明日10時の仮リリースまでに **必ず** 実行してもらいます。

**Comment by SoyaTakahashi** [comment]
## ToDo

- [ ] アバター画像の保存先をs3にする
- [ ] コメント機能を実装
- [ ] つぶやき/ブログにデータを反映させる
- [ ] faviconの設定
- [ ] 地域イベントの仮データをどうするか矢倉先輩と話し合う
- [ ] サロンを予約する機能を実装


## 困っていること

- awsアカウントの使用ができず、s3が使用できない
  - 矢倉先輩のクレジットカードが原因？？

**Comment by kaorioyama** [comment]
## ToDo

- [ ] デザインの見直し

**Comment by MaiKambe** [comment]
## ToDo

- [ ] 通知ページのデザインを変更
- [ ] 地域情報ページのデザイン見直し(各イベントの間に空白を入れるなど)

**Comment by KarenNakayama** [comment]
## ToDo

- [ ] デザインの直し

- [ ] 予約一覧をポップアップウィンドではなくする

**Comment by kota226** [comment]
## ToDo
デザインの見直し

**Comment by kota226** [comment]
## 困っていること

- [ ] 競合が発生（高橋くんと共同で修正する必要がある）

- [ ] blogs.controller

- [ ] murmurs.controller

- [ ] blogs.index.html

- [ ] murmurs.index.html
