### ISSUE TITLE
年と月を選ぶプルダウンの境界が無くなってて、見えづらい印象を受けました。

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#237]
## WHAT

年と月を選ぶプルダウンの境界が無くなってて、見えづらい印象を受けました。

<img width="960" alt="00e8ca22-c52c-11e6-8043-c67d0cd27535" src="https://cloud.githubusercontent.com/assets/11175160/21412816/6cbb794a-c836-11e6-9027-72c9473cf3d7.png">

**Comment by MaiKambe** [comment]
修正完了したため、閉じます
