### ISSUE TITLE
地域のイベントページの夏祭りの内容が空

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#240]
## 地域のイベントページの夏祭りの内容が空

<img width="1007" alt="8ef40f6e-c533-11e6-8829-5b0905301f84" src="https://cloud.githubusercontent.com/assets/11175160/21412933/301105cc-c837-11e6-8b6e-c485159b3a3f.png">

**Comment by MaiKambe** [comment]
先輩が書いてくださいました
