### ISSUE TITLE
SNSのトップページのデザイン

### ISSUE THREAD

**Issue by KarenNakayama** [KanseiLab/sns#4]
![default](https://cloud.githubusercontent.com/assets/19641677/16876268/379680be-4ade-11e6-895c-110616ba8558.png)
![default](https://cloud.githubusercontent.com/assets/19641677/16876266/3775716c-4ade-11e6-9463-0138f1544217.png)

まいさんのデザインで自分配置にさせてもらいました。
掲示板は投稿一覧の間違えです(； ･`д･´)
アイコンは適当なので悪しからず。

**Comment by SoyaTakahashi** [comment]
間違って作ったissueです。
