### ISSUE TITLE
各ページのデザインFB

### ISSUE THREAD

**Issue by SoyaTakahashi** [KanseiLab/sns#69]
## What

今回作成したページそれぞれFBします。
## Where

もっとよくできるから

**Comment by SoyaTakahashi** [comment]
## 新規登録ページ
- [ ] スクロールするとヘッダーのしたにもぐる
- [ ] 登録ボタンの色を強調する
- [ ] 見た目がくずれている
- [ ] 枠線の色を薄くする

## フッダー
- [ ] 一番下にきていない

## 地域情報ページ
- [ ] 表示が重なっている
- [ ] フッターが入っている

## 通知ページ
- [ ] フッターがずれいてる
- [ ] 日時と四角の幅がせまい

## 予約ページ
- [ ]  ページがくずれている

## マイページ
- [ ] 謎の四角がある
- [ ] submitボタンがおかしい

## お問い合わせページ
- [ ] ページがくずれている
- [ ] 項目の色変える

## ブログ投稿ページ
- [ ] 書くboxを左ぞろえにする

## つぶやきページ
- [ ] つぶやく（250文字まで）とtext-areaの幅が大きくすぎる

**Comment by kota226** [comment]
フッターなのですが、ページによって下にできる余白の高さが異なる不具合があるようで、自分の担当していた投稿一覧のページを基準に位置を調整してあります。

**Comment by SoyaTakahashi** [comment]
## チェックした人

- [ ] 矢倉さん
- [ ] かれんさん
- [ ] 大山さん
- [ ] 神戸さん

**Comment by KarenNakayama** [comment]
問い合わせページの問い合わせのボタンの位置
（と、つぶやきページのボタンの大きさ）を修正したいと思いました。

**Comment by SoyaTakahashi** [comment]
@KarenNakayama 
いいですね！修正しちゃいましょう！！

**Comment by MaiKambe** [comment]
フッターのずれと表示の重なりがこちら視点で確認できず、どう修正すれば良いかわかりません…

**Comment by SoyaTakahashi** [comment]
`地域情報ページ` は大山さんかな？

**Comment by MaiKambe** [comment]
すみません、地域情報と通知は私です

**Comment by SoyaTakahashi** [comment]
@MaiKambe 
まだ直っていないかんじですか？

**Comment by MaiKambe** [comment]
@SoyaTakahashi 
masterで現在確認できない様なので作業ブランチでそれぞれのページを確認しましたが、
フッターは正常で、他の表示も特に異常がないので手を付けようにも…といった感じです。

**Comment by SoyaTakahashi** [comment]
@MaiKambe 
> masterで現在確認できない様なので

masterで確認できますよん！

**Comment by MaiKambe** [comment]
@SoyaTakahashi 
masterに移動すると開けなくて…

**Comment by MaiKambe** [comment]
@SoyaTakahashi 
![2016-11-21 am0 54 00](https://cloud.githubusercontent.com/assets/19641679/20464151/ca4afa1e-af85-11e6-8b30-aaab7d358e28.png)

**Comment by SoyaTakahashi** [comment]
@MaiKambe 
あ、こういうのはslackでお願い！

**Comment by kaorioyama** [comment]
masterで開くとデザインが崩れます
